dubbo:
  application:
    name: car-api-provider
    qos-port: 22222
    metadataServicePort: 20885
    qosEnable: true
    qosAcceptForeignIp: true
  protocol:
    name: tri
    port: 50051
  registry:
    address: N/A
  rpc:
    tri:
      initial-window-size: 1048576
  tri:
    builtin:
      service:
        init: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: ${spring.profiles.active}
  redis:
    database: 0
    timeout: 60s
    jedis:
      pool:
        max-active: 16
        max-idle: 16
        min-idle: 8

logging:
  level:
    org.springframework.data.redis.listener.RedisMessageListenerContainer: off

