spring:
  profiles:
    active: ${spring.profiles.active}
  redis:
    database: 0
    timeout: 60s
    jedis:
      pool:
        max-active: 16
        max-idle: 16
        min-idle: 8


logging:
  level:
    org.springframework.data.redis.listener.RedisMessageListenerContainer: off



